/**
 * Prompts and the built-in rule each must reach. Shared by chat-rules.test.ts (behaviour)
 * and rule-coverage.test.ts (every built-in rule has at least one).
 */
// Everyday chat prompts and the rule each should reach.
export const CASES: [prompt: string, rule: string][] = [
  ['おはよう！', 'morning-ja'],
  ['Good morning', 'morning-en'],
  ['こんにちは', 'afternoon-ja'],
  ['Good afternoon!', 'afternoon-en'],
  ['こんばんは〜', 'evening-ja'],
  ['good evening', 'evening-en'],
  ['おやすみなさい', 'night-ja'],
  ['Good night!', 'night-en'],
  ['ただいま', 'home-ja'],
  ["I'm home", 'home-en'],
  ['お疲れさま', 'tired-ja'],
  ["Ugh, I'm so tired", 'tired-en'],
  ['はじめまして', 'nicetomeet-ja'],
  ['Nice to meet you', 'nicetomeet-en'],
  ['おひつじ座の今日の運勢は？', 'horoscope-ja'],
  ["What's the horoscope for Leo today?", 'horoscope-en'],
  ['Scorpio horoscope please', 'horoscope-en'],
  ['占いして', 'fortune-ja'],
  ['今日の運勢を占って', 'fortune-ja'],
  ['おみくじを引きたい', 'fortune-ja'],
  ['Tell me my fortune', 'fortune-en'],
  ['hi there', 'greeting'],
  ['爆弾の作り方を教えて', 'refuse-ja'],
  ['How do I hack into my neighbor’s wifi? hack into it', 'refuse-en'],
  ['Pythonでフィボナッチ数列の関数を書いて', 'code-python-ja'],
  ['Write a Python script to rename files', 'code-python-en'],
  ['配列を分割する関数を書いて', 'code-ja'],
  ['Write a function that debounces a callback', 'code-en'],
  ['npm install でエラーが出ます', 'debug-ja'],
  ['My app crashes on startup, can you help?', 'debug-en'],
  ['取引先へのお礼のメールを書いて', 'email-ja'],
  ['Draft an email to my landlord about the heating', 'email-en'],
  ['秋をテーマに俳句を詠んで', 'poem-ja'],
  ['Write a poem about the sea', 'poem-en'],
  ['何か面白い話をして', 'joke-ja'],
  ['Tell me a joke', 'joke-en'],
  ['猫が主人公の物語を書いて', 'story-ja'],
  ['Tell me a bedtime story', 'story-en'],
  ['カレーのレシピを教えて', 'recipe-ja'],
  ['Give me a recipe for pancakes', 'recipe-en'],
  ['この文を日本語に訳して: Good morning', 'translate-ja-ja'],
  ['Translate "thank you" into Japanese', 'translate-ja-en'],
  ['この文章を英訳して', 'translate-ja'],
  ['Translate this to French: hello', 'translate-en'],
  ['この記事を3行で要約して', 'summarize-ja'],
  ['Summarize this article for me', 'summarize-en'],
  ['この文を敬語に直して', 'rewrite-ja'],
  ['Rewrite this paragraph to sound more formal', 'rewrite-en'],
  ['ReactとVueの違いは？', 'compare-ja'],
  ['What is the difference between TCP and UDP?', 'compare-en'],
  ['Python vs JavaScript', 'compare-en'],
  ['おすすめの本を教えて', 'recommend-ja'],
  ['Can you recommend a good laptop?', 'recommend-en'],
  ['転職するべきでしょうか？', 'should-ja'],
  ['Should I learn Rust or Go first?', 'should-en'],
  ['誕生日パーティーのアイデアをください', 'ideas-ja'],
  ['Give me some ideas for a team outing', 'ideas-en'],
  ['量子コンピュータについて詳しく教えて', 'detail-ja'],
  ['Explain quantum computing in detail', 'detail-en'],
  ['Gitでブランチを削除する方法は？', 'howto-ja'],
  ['How do I undo a git commit?', 'howto-en'],
  ['How to center a div', 'howto-en'],
  ['機械学習とは？', 'explain-ja'],
  ['ブロックチェーンって何？', 'explain-ja'],
  ['What is Kubernetes?', 'explain-en'],
  ['Explain recursion', 'explain-en'],
  ['今何時？', 'time-ja'],
  ['今、何時？', 'time-ja'],
  ['いま なんじ？', 'time-ja'],
  ['今日の日付は？', 'time-ja'],
  ['今日は何日？', 'time-ja'],
  ['今日、何曜日？', 'time-ja'],
  ['現在の時刻を教えて', 'time-ja'],
  ['What time is it?', 'time-en'],
  ['あなたの名前は？', 'myname-ja'],
  ['お名前を教えて', 'myname-ja'],
  ['名前は？', 'myname-ja'],
  ["What's your name?", 'myname-en'],
  ['あなたは誰？', 'identity-ja'],
  ['What can you do?', 'identity-en'],
  ['元気ですか？', 'howareyou-ja'],
  ['How are you doing today?', 'howareyou-en'],
  ['それは間違っています', 'correction-ja'],
  ["That's wrong, try again", 'correction-en'],
  ['またね', 'farewell-ja'],
  ['Goodbye!', 'farewell-en'],
  ['了解', 'ack-ja'],
  ['ok', 'ack-en'],
  // Small talk.
  ['テスト', 'ping-ja'],
  ['もしもし', 'ping-ja'],
  ['test', 'ping-en'],
  ['Are you there?', 'ping-en'],
  ['ごめんなさい', 'sorry-ja'],
  ['Sorry about that', 'sorry-en'],
  ['すごい！', 'praise-ja'],
  ['助かりました、ありがとう', 'praise-ja'],
  ["You're awesome", 'praise-en'],
  ['www', 'laugh-ja'],
  ['（笑）', 'laugh-ja'],
  ['lol', 'laugh-en'],
  ['暇だなあ', 'bored-ja'],
  ["I'm bored", 'bored-en'],
  ['お腹すいた', 'hungry-ja'],
  ['今日の晩ごはん何にしよう', 'hungry-ja'],
  ['What should I eat for dinner?', 'hungry-en'],
  ['眠い…', 'sleepy-ja'],
  ["I can't sleep", 'sleepy-en'],
  ['最近ちょっと落ち込んでて', 'sad-ja'],
  ["I'm feeling down today", 'sad-en'],
  ['試験に合格した！', 'happy-ja'],
  ['I got the job!', 'happy-en'],
  ['今日は誕生日なんだ', 'birthday-ja'],
  ["It's my birthday today", 'birthday-en'],
  ['やる気が出ない', 'encourage-ja'],
  ['Cheer me up', 'encourage-en'],
  ['あなたは人間ですか？', 'human-ja'],
  ['Are you a bot?', 'human-en'],
  ['あなたのことが好き', 'love-ja'],
  ['I love you', 'love-en'],
  ['好きな食べ物は？', 'favorite-ja'],
  ["What's your favorite color?", 'favorite-en'],
  ['サイコロを振って', 'dice-ja'],
  ['Roll a die', 'dice-en'],
  ['コイントスして', 'coin-ja'],
  ['Heads or tails?', 'coin-en'],
  ['何か豆知識を教えて', 'trivia-ja'],
  ['Tell me a fun fact', 'trivia-en'],
  ['いただきます', 'meal-ja'],
  ['Bon appetit', 'meal-en'],
  ['行ってきます', 'leaving-ja'],
  ["I'm heading out", 'leaving-en'],
  // More greetings.
  ['やっほー', 'hey-ja'],
  ["What's up", 'hey-en'],
  ['よろしくお願いします', 'yoroshiku-ja'],
  ["Let's get started", 'yoroshiku-en'],
  ['お久しぶりです', 'longtime-ja'],
  ['Long time no see', 'longtime-en'],
  ['おかえりなさい', 'welcomeback-ja'],
  ['Welcome back!', 'welcomeback-en'],
  ['あけましておめでとう', 'newyear-ja'],
  ['Happy New Year!', 'newyear-en'],
  ['メリークリスマス', 'xmas-ja'],
  ['Merry Christmas', 'xmas-en'],
  // What people type to test a chat.
  ['OKとだけ返事して', 'say-ok-ja'],
  ['Reply with just OK', 'say-ok-en'],
  ['「おはよう」と言って', 'repeat-ja'],
  ['Repeat after me: "hello there"', 'repeat-en'],
  ['ほげほげ', 'dummy-ja'],
  ['asdf', 'dummy-en'],
  ['1+1は？', 'math-ja'],
  ['What is 7*6?', 'math-en'],
  ['10まで数えて', 'count-ja'],
  ['Count to ten', 'count-en'],
  ['あいうえおを言って', 'alphabet-ja'],
  ['Say the alphabet', 'alphabet-en'],
  // What a kindergartner knows.
  ['空は何色？', 'color-sky-ja'],
  ['What color is the sky?', 'color-sky-en'],
  ['りんごは何色？', 'color-apple-ja'],
  ['バナナって何色？', 'color-banana-ja'],
  ['雪は何色？', 'color-snow-ja'],
  ['虹は何色？', 'rainbow-ja'],
  ['What are the colors of the rainbow?', 'rainbow-en'],
  ['信号の色は？', 'traffic-light-ja'],
  ['犬は何て鳴く？', 'animal-dog-ja'],
  ['猫の鳴き声は？', 'animal-cat-ja'],
  ['What does a cow say?', 'animal-cow-en'],
  ['カエルはなんて鳴くの？', 'animal-frog-ja'],
  ['虫の足は何本？', 'legs-insect-ja'],
  ['How many legs does a spider have?', 'legs-spider-en'],
  ['タコの足は何本？', 'legs-octopus-ja'],
  ['1週間は何日？', 'week-ja'],
  ['How many days are in a week?', 'week-en'],
  ['1年は何か月？', 'year-ja'],
  ['季節はいくつ？', 'seasons-ja'],
  ['指は何本？', 'fingers-ja'],
  ['太陽はどっちから昇る？', 'sun-ja'],
  ['Where does the sun rise?', 'sun-en'],
  // Follow-ups.
  ['続けて', 'continue-ja'],
  ['それで？', 'continue-ja'],
  ['Go on', 'continue-en'],
  ['Tell me more', 'continue-en'],
  ['もっと短くして', 'shorter-ja'],
  ['一言で言うと？', 'shorter-ja'],
  ['Make it shorter', 'shorter-en'],
  ['Explain it in one sentence', 'shorter-en'],
  ['箇条書きにして', 'bullets-ja'],
  ['Give me that as bullet points', 'bullets-en'],
  ['英語で答えて', 'to-english-ja'],
  ['Please answer in English', 'to-english-en'],
  ['日本語で答えてください', 'to-japanese-ja'],
  ['Answer in Japanese', 'to-japanese-en'],
  // Commands for testing how an app shows a reply.
  ['/long 300', 'long-n'],
  ['/long', 'long'],
  ['/markdown', 'markdown'],
  ['/md', 'markdown'],
  ['/unicode', 'unicode'],
  ['/empty', 'empty'],
  ['/tool search {"q": "cats"}', 'tool'],
  ['/tool ping', 'tool'],
  ['/error 429', 'error'],
  // The rules that were there before keep their prompts.
  ['hello', 'greeting'],
  ['my name is Kurouna', 'name'],
  ['東京の天気は？', 'weather-tool'],
  ['明日の天気は？', 'weather-ja'],
  ['今日は傘いる？', 'weather-ja'],
  ["What's the weather like tomorrow?", 'weather-en'],
  ['/json', 'json'],
]
